name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Lightsail
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ${{ secrets.TARGET_DIR }}
          git pull origin main
          npm install
          pm2 restart all
